// flow-typed signature: 4a71ba254240b928035bf08c0972ca17
// flow-typed version: <<STUB>>/color_v^3.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'color'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'color' {
  declare export type RGB = { r: number, g: number, b: number };
  declare export type ColorInput = string | RGB;
  declare export interface ColorFactory {
    (c: ColorInput): Color;
    rgb(c: Array<number>): Color;
    rgb(...c: Array<number>): Color;
  }

  declare export interface Color {
    toString(): string;
    string(): string;
    hsl(): string;
    object(): RGB;
    rgbNumber(): number;
    red(): number;
    green(): number;
    blue(): number;
    isLight(): boolean;
    isDark(): boolean;
    negate(): Color;
    darken(amount: number): Color;
    saturate(amount: number): Color;
    desaturate(amount: number): Color;
    grayscale(): Color;
    whiten(amount: number): Color;
    blacken(amount: number): Color;
    fade(amount: number): Color;
    opaquer(amount: number): Color;
    rotate(angle: number): Color;
    mix(c: Color): Color;
  }

  declare export default ColorFactory;
}
